/**
 * Practice Texts Configuration
 * Organized by HSK level
 * Examples will be generated by Groq AI
 */

const groqService = require('../services/groq');

/**
 * Base practice texts by HSK level
 * These are the core texts, examples will be generated by Groq
 */
const BASE_PRACTICE_TEXTS = {
    1: [
        { id: 1, text: '你好', pinyin: 'nǐ hǎo', meaning: 'Xin chào' },
        { id: 2, text: '谢谢', pinyin: 'xiè xie', meaning: 'Cảm ơn' },
        { id: 3, text: '再见', pinyin: 'zài jiàn', meaning: 'Tạm biệt' },
        { id: 4, text: '对不起', pinyin: 'duì bu qǐ', meaning: 'Xin lỗi' },
        { id: 5, text: '没关系', pinyin: 'méi guān xi', meaning: 'Không sao' },
        { id: 6, text: '我很好', pinyin: 'wǒ hěn hǎo', meaning: 'Tôi rất tốt' },
        { id: 7, text: '你叫什么名字', pinyin: 'nǐ jiào shén me míng zi', meaning: 'Bạn tên là gì' },
        { id: 8, text: '我是中国人', pinyin: 'wǒ shì zhōng guó rén', meaning: 'Tôi là người Trung Quốc' },
        { id: 9, text: '很高兴认识你', pinyin: 'hěn gāo xìng rèn shi nǐ', meaning: 'Rất vui được gặp bạn' },
        { id: 10, text: '今天天气很好', pinyin: 'jīn tiān tiān qì hěn hǎo', meaning: 'Hôm nay trời rất đẹp' },
    ],
    2: [
        { id: 11, text: '我想学中文', pinyin: 'wǒ xiǎng xué zhōng wén', meaning: 'Tôi muốn học tiếng Trung' },
        { id: 12, text: '这个多少钱', pinyin: 'zhè ge duō shǎo qián', meaning: 'Cái này bao nhiêu tiền' },
        { id: 13, text: '我有一个问题', pinyin: 'wǒ yǒu yī gè wèn tí', meaning: 'Tôi có một câu hỏi' },
        { id: 14, text: '你能帮我吗', pinyin: 'nǐ néng bāng wǒ ma', meaning: 'Bạn có thể giúp tôi không' },
        { id: 15, text: '我不明白', pinyin: 'wǒ bù míng bai', meaning: 'Tôi không hiểu' },
        { id: 16, text: '请再说一遍', pinyin: 'qǐng zài shuō yī biàn', meaning: 'Xin hãy nói lại một lần' },
        { id: 17, text: '我有点累', pinyin: 'wǒ yǒu diǎn lèi', meaning: 'Tôi hơi mệt' },
        { id: 18, text: '现在几点了', pinyin: 'xiàn zài jǐ diǎn le', meaning: 'Bây giờ mấy giờ rồi' },
        { id: 19, text: '我饿了', pinyin: 'wǒ è le', meaning: 'Tôi đói rồi' },
        { id: 20, text: '我想喝水', pinyin: 'wǒ xiǎng hē shuǐ', meaning: 'Tôi muốn uống nước' },
    ],
    3: [
        { id: 21, text: '我每天早上七点起床', pinyin: 'wǒ měi tiān zǎo shang qī diǎn qǐ chuáng', meaning: 'Tôi mỗi ngày sáng 7 giờ dậy' },
        { id: 22, text: '我喜欢吃中国菜', pinyin: 'wǒ xǐ huan chī zhōng guó cài', meaning: 'Tôi thích ăn món Trung Quốc' },
        { id: 23, text: '这个周末你有什么计划', pinyin: 'zhè ge zhōu mò nǐ yǒu shén me jì huà', meaning: 'Cuối tuần này bạn có kế hoạch gì' },
        { id: 24, text: '我正在学习汉语', pinyin: 'wǒ zhèng zài xué xí hàn yǔ', meaning: 'Tôi đang học tiếng Trung' },
        { id: 25, text: '你觉得这个怎么样', pinyin: 'nǐ jué de zhè ge zěn me yàng', meaning: 'Bạn thấy cái này thế nào' },
        { id: 26, text: '我有点忙', pinyin: 'wǒ yǒu diǎn máng', meaning: 'Tôi hơi bận' },
        { id: 27, text: '你能告诉我怎么去吗', pinyin: 'nǐ néng gào su wǒ zěn me qù ma', meaning: 'Bạn có thể nói cho tôi biết cách đi không' },
        { id: 28, text: '我需要买一些东西', pinyin: 'wǒ xū yào mǎi yī xiē dōng xi', meaning: 'Tôi cần mua một số thứ' },
        { id: 29, text: '这个房间很大', pinyin: 'zhè ge fáng jiān hěn dà', meaning: 'Căn phòng này rất lớn' },
        { id: 30, text: '我经常去图书馆', pinyin: 'wǒ jīng cháng qù tú shū guǎn', meaning: 'Tôi thường xuyên đi thư viện' },
    ],
    4: [
        { id: 31, text: '我对中国文化很感兴趣', pinyin: 'wǒ duì zhōng guó wén huà hěn gǎn xìng qù', meaning: 'Tôi rất quan tâm đến văn hóa Trung Quốc' },
        { id: 32, text: '这个决定对我来说很重要', pinyin: 'zhè ge jué dìng duì wǒ lái shuō hěn zhòng yào', meaning: 'Quyết định này rất quan trọng đối với tôi' },
        { id: 33, text: '我希望能提高我的汉语水平', pinyin: 'wǒ xī wàng néng tí gāo wǒ de hàn yǔ shuǐ píng', meaning: 'Tôi hy vọng có thể nâng cao trình độ tiếng Trung của mình' },
        { id: 34, text: '这个方法看起来很有效', pinyin: 'zhè ge fāng fǎ kàn qǐ lái hěn yǒu xiào', meaning: 'Phương pháp này có vẻ rất hiệu quả' },
        { id: 35, text: '我需要更多时间来准备', pinyin: 'wǒ xū yào gèng duō shí jiān lái zhǔn bèi', meaning: 'Tôi cần nhiều thời gian hơn để chuẩn bị' },
        { id: 36, text: '这个城市很漂亮', pinyin: 'zhè ge chéng shì hěn piào liang', meaning: 'Thành phố này rất đẹp' },
        { id: 37, text: '我喜欢这个颜色', pinyin: 'wǒ xǐ huan zhè ge yán sè', meaning: 'Tôi thích màu này' },
        { id: 38, text: '这个菜很好吃', pinyin: 'zhè ge cài hěn hǎo chī', meaning: 'Món này rất ngon' },
        { id: 39, text: '这个房间很干净', pinyin: 'zhè ge fáng jiān hěn gān jìng', meaning: 'Căn phòng này rất sạch' },
        { id: 40, text: '这个天气很舒服', pinyin: 'zhè ge tiān qì hěn shū fu', meaning: 'Thời tiết này rất dễ chịu' },
    ],
    5: [
        { id: 41, text: '随着科技的发展，人们的生活方式发生了很大变化', pinyin: 'suí zhe kē jì de fā zhǎn, rén men de shēng huó fāng shì fā shēng le hěn dà biàn huà', meaning: 'Với sự phát triển của công nghệ, lối sống của con người đã thay đổi rất nhiều' },
        { id: 42, text: '这个问题的解决需要多方面的合作', pinyin: 'zhè ge wèn tí de jiě jué xū yào duō fāng miàn de hé zuò', meaning: 'Việc giải quyết vấn đề này cần sự hợp tác từ nhiều phía' },
        { id: 43, text: '我们应该重视环境保护的重要性', pinyin: 'wǒ men yīng gāi zhòng shì huán jìng bǎo hù de zhòng yào xìng', meaning: 'Chúng ta nên coi trọng tầm quan trọng của việc bảo vệ môi trường' },
        { id: 44, text: '这个项目对我们的公司来说是一个重要的机会', pinyin: 'zhè ge xiàng mù duì wǒ men de gōng sī lái shuō shì yī gè zhòng yào de jī huì', meaning: 'Dự án này đối với công ty của chúng ta là một cơ hội quan trọng' },
        { id: 45, text: '我建议我们采取更加积极的态度来面对这个挑战', pinyin: 'wǒ jiàn yì wǒ men cǎi qǔ gèng jiā jī jí de tài dù lái miàn duì zhè ge tiǎo zhàn', meaning: 'Tôi đề xuất chúng ta nên thái độ tích cực hơn để đối mặt với thách thức này' },
        { id: 46, text: '这个计划需要仔细考虑', pinyin: 'zhè ge jì huà xū yào zǐ xì kǎo lǜ', meaning: 'Kế hoạch này cần cân nhắc kỹ càng' },
        { id: 47, text: '这个团队很有经验', pinyin: 'zhè ge tuán duì hěn yǒu jīng yàn', meaning: 'Đội ngũ này rất có kinh nghiệm' },
        { id: 48, text: '这个市场很有潜力', pinyin: 'zhè ge shì chǎng hěn yǒu qián lì', meaning: 'Thị trường này rất có tiềm năng' },
        { id: 49, text: '这个产品很受欢迎', pinyin: 'zhè ge chǎn pǐn hěn shòu huān yíng', meaning: 'Sản phẩm này rất được ưa chuộng' },
        { id: 50, text: '这个技术很先进', pinyin: 'zhè ge jì shù hěn xiān jìn', meaning: 'Công nghệ này rất tiên tiến' },
    ],
    6: [
        { id: 51, text: '在当今全球化的背景下，跨文化交流变得越来越重要', pinyin: 'zài dāng jīn quán qiú huà de bèi jǐng xià, kuà wén huà jiāo liú biàn de yuè lái yuè zhòng yào', meaning: 'Trong bối cảnh toàn cầu hóa hiện nay, giao lưu văn hóa trở nên ngày càng quan trọng' },
        { id: 52, text: '这个理论在实践中得到了充分的验证', pinyin: 'zhè ge lǐ lùn zài shí jiàn zhōng dé dào le chōng fèn de yàn zhèng', meaning: 'Lý thuyết này đã được kiểm chứng đầy đủ trong thực tế' },
        { id: 53, text: '我们应该从历史中吸取教训，避免重复同样的错误', pinyin: 'wǒ men yīng gāi cóng lì shǐ zhōng xī qǔ jiào xùn, bì miǎn chóng fù tóng yàng de cuò wù', meaning: 'Chúng ta nên rút ra bài học từ lịch sử để tránh lặp lại những sai lầm tương tự' },
        { id: 54, text: '这个创新的方法为解决复杂问题提供了新的思路', pinyin: 'zhè ge chuàng xīn de fāng fǎ wèi jiě jué fù zá wèn tí tí gōng le xīn de sī lù', meaning: 'Phương pháp sáng tạo này cung cấp tư duy mới để giải quyết các vấn đề phức tạp' },
        { id: 55, text: '在追求个人发展的同时，我们也应该关注社会责任', pinyin: 'zài zhuī qiú gè rén fā zhǎn de tóng shí, wǒ men yě yīng gāi guān zhù shè huì zé rèn', meaning: 'Khi theo đuổi phát triển cá nhân, chúng ta cũng nên quan tâm đến trách nhiệm xã hội' },
        { id: 56, text: '这个社会需要更多的理解和支持', pinyin: 'zhè ge shè huì xū yào gèng duō de lǐ jiě hé zhī chí', meaning: 'Xã hội này cần nhiều sự hiểu và hỗ trợ hơn' },
        { id: 57, text: '这个政策需要更多的讨论', pinyin: 'zhè ge zhèng cè xū yào gèng duō de tǎo lùn', meaning: 'Chính sách này cần nhiều thảo luận hơn' },
        { id: 58, text: '这个项目需要更多的资源', pinyin: 'zhè ge xiàng mù xū yào gèng duō de zī yuán', meaning: 'Dự án này cần nhiều nguồn lực hơn' },
        { id: 59, text: '这个挑战需要更多的勇气', pinyin: 'zhè ge tiǎo zhàn xū yào gèng duō de yǒng qì', meaning: 'Thách thức này cần nhiều can đảm hơn' },
        { id: 60, text: '这个机会需要更多的准备', pinyin: 'zhè ge jī huì xū yào gèng duō de zhǔn bèi', meaning: 'Cơ hội này cần nhiều chuẩn bị hơn' },
    ],
};

/**
 * Generate example sentences using Groq AI
 * @param {string} text - The practice text
 * @param {number} hskLevel - HSK level
 * @returns {Promise<string>} - Example sentence
 */
async function generateExample(text, hskLevel) {
    try {
        const systemPrompt = `Bạn là giáo viên tiếng Trung chuyên nghiệp.
Nhiệm vụ: Tạo 1 câu ví dụ ngắn (dưới 15 chữ) sử dụng từ "${text}".
Quy tắc:
- Chỉ dùng từ vựng HSK ${hskLevel} trở xuống
- Câu phải tự nhiên, dễ hiểu
- Trả về JSON format: {"example": "câu ví dụ", "pinyin": "phiên âm", "meaning": "nghĩa tiếng Việt"}
- KHÔNG dùng markdown, chỉ JSON thuần`;

        const messages = [
            { role: 'system', content: systemPrompt },
            { role: 'user', content: `Tạo câu ví dụ với từ "${text}"` }
        ];

        const result = await groqService.sendMessage(messages, 'practice-example-' + Date.now());

        // Parse JSON response
        try {
            const parsed = JSON.parse(result.text);
            return parsed.example || result.text;
        } catch {
            // If JSON parsing fails, return the raw text
            return result.text;
        }
    } catch (error) {
        console.error('Failed to generate example with Groq:', error);
        // Fallback: return a simple example
        return `这是${text}的例子。`;
    }
}

/**
 * Get practice text by HSK level
 * @param {number} level - HSK level (1-6)
 * @param {boolean} generateExamples - Whether to generate examples with Groq
 * @returns {Promise<Object>} - Random practice text with optional example
 */
async function getPracticeText(level, generateExamples = false) {
    const texts = BASE_PRACTICE_TEXTS[level] || BASE_PRACTICE_TEXTS[1];
    const randomIndex = Math.floor(Math.random() * texts.length);
    const text = texts[randomIndex];

    // Generate example if requested
    let example = null;
    if (generateExamples) {
        try {
            example = await generateExample(text.text, level);
        } catch (error) {
            console.error('Failed to generate example:', error);
        }
    }

    return {
        ...text,
        example
    };
}

/**
 * Get all practice texts by HSK level
 * @param {number} level - HSK level (1-6)
 * @returns {Array} - All practice texts for the level
 */
function getPracticeTextsByLevel(level) {
    return BASE_PRACTICE_TEXTS[level] || BASE_PRACTICE_TEXTS[1];
}

module.exports = {
    BASE_PRACTICE_TEXTS,
    getPracticeText,
    getPracticeTextsByLevel,
    generateExample
};